import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import { useRouter } from 'next/router';
import { useRef } from 'react';
import { postApi } from '../lib/api';

const Home: NextPage = () => {
  const router = useRouter();
  const file = useRef<HTMLInputElement>(null);

  const handleInputFile = async (e: any) => {
    const files = e.target.files;

    let img_url = URL.createObjectURL(files[0]);
    const result = await postApi.postImageFile(files[0]);
    console.log(result);
    const len = e.target.files.length;
    router.push(`/result/?imageID=${result.imageId}`);
  };

  
  return (
    <div className={styles.container}>
      <Head>
        <title>Catch App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          숙명여대 졸업 프로젝트{' '}
          <code className={styles.code}>다빈, 수현, 우진 </code>
        </p>
        <div className={styles.button_cntr}>
          <label className={styles.button} htmlFor="img_trash">
            파일 업로드하기
            <input
              type="file"
              id="img_trash"
              accept="image/jpeg, image/jpg, image/png"
              multiple={false}
              ref={file}
              onChange={handleInputFile}
              style={{ width: '0', height: '0' }}
            />
          </label>
          <div className={styles.button} onClick={() => router.push('/upload')}>
            촬영하기
          </div>
        </div>
      </main>
    </div>
  );
};

export default Home;
